id: P001736
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-17 10:17:32.998547
source_metadata:
  id: bdr:W3CN4660
  title: བསྐྱེད་རྫོགས་ཟུང་འཇུག་གི་མན་ངག་ལམ་འབྲས་བུ་དང་བཅས་པའི་ཆོས་སྐོར།
  author: ''
  volumes:
    3f6f093981c941a3b7eb3dd1fa5ab255:
      image_group_id: I3CN4662
      title: ''
      volume_number: 1
      total_pages: 548
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
